name: msk
description: A new flutter plugin project.
version: 1.0.1
homepage:
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cpf_cnpj_validator: ^2.0.0
  queue: ^3.1.0+1
  midia_select:
    #path: /Users/reni/Downloads/Projetos/MSK/flutter/msk_plugin/midia_select/
    #path: "C:/Users/reni/Downloads/Projetos/flutter/libs/midia_select"
    git:
      url: https://github.com/ReniDelonzek/midia_select.git
      ref: 360f17c52d3aee70801b6931acbe99c1a8989540
  file_picker_cross: ^4.4.2
  shared_preferences: ^2.0.6
  printing: ^5.5.0
  google_fonts: ^3.0.1
  #flutter_local_notifications:
   # git:
    #  url: https://github.com/ened/flutter_local_notifications.git
     # path: flutter_local_notifications
      #ref: c21f8fc0e56477f7053b1bf1b4fa46290f8e5e8b
   
  sortedmap: ^0.5.1
  get_it: ^7.2.0
  screenshot: ^1.2.3
  signature: ^4.1.1
  msk_widgets:
    #path: /Users/reni/Downloads/Projetos/MSK/flutter/msk_plugin/msk_widgets
    #path: "C:/Users/reni/Downloads/Projetos/agro/libs/msk_widgets"
    git:
      url: git@github.com:aynova-tecnologia/msk_widgets.git
      ref: a375825ee7de509bb1edd83fee581b718b021b4c
  auth_interface:
    #path: /Users/reni/Downloads/Projetos/MSK/flutter/msk_plugin/auth_interface
    git:
      url: git@github.com:aynova-tecnologia/auth_interface.git 
      ref: ba6984422b5281c66546f793022e0eec607dc5ee
    

  after_layout: ^1.1.0
  firebase_core: "1.10.0"
  package_info: ^2.0.2
  image_picker: ^0.8.3
  msk_utils: ">=1.0.4"
  # versao mais recente obriga a colocar versao do android 24 como minima
  # Cuidar para não colocar o clique de abrir a tela dentro de um input, pois isso pode causar crash ao app
    #git:
     # path: qrcode
      #url: git@github.com:SiriDx/qrcode.git
      #ref: 7249dba8074ae4c42394a998b07b31133c9e12ff
  url_launcher: ^6.0.9
  flutter_local_notifications: ^9.2.0
  firebase_messaging: ^10.0.5
  #versao funcionando no IOS
  #firebase_messaging: ^6.0.13
  sprintf: ^6.0.0
  device_info: ^2.0.2
  connectivity_plus: ^2.0.3
  #connectivity: ^2.0.2
  flutter_secure_storage: ^5.0.2
  sqfentity: "2.2.0+6"
    #path: /Users/reni/Downloads/Projetos/Flutter/libs/sqfEntity/sqfentity
    # git: 
    #   url: https://github.com/aynova-tecnologia/sqfEntity.git
    #   path: sqfentity
    #   ref: 299acbe96d8e7b215378bd1dcb4a323608c8714a
  firebase_storage: ^10.0.2
  hive_flutter: ^1.1.0
  hive: ^2.0.4
  mobx: ^2.0.4
  dio: ^4.0.0

  flutter:
    sdk: flutter  
  flutter_localizations:
    sdk: flutter


dependency_overrides:
#   intl: 0.17.0
#   path_provider: ^2.0.1 
#   mobx_codegen: ^1.1.2
#   mobx: ^1.1.0
#   flutter_mobx: ^1.1.0+2
  #sqlite3: '>=1.0.0 <3.0.0'
  #flutter_local_notifications:
   # git:
    #  url: https://github.com/ened/flutter_local_notifications.git
     # path: flutter_local_notifications
     # ref: c21f8fc0e56477f7053b1bf1b4fa46290f8e5e8b
  #flutter_local_notifications_platform_interface:
   # git:
    #  url: https://github.com/ened/flutter_local_notifications.git
     # path: flutter_local_notifications_platform_interface
      #ref: c21f8fc0e56477f7053b1bf1b4fa46290f8e5e8b
  

dev_dependencies:
  sqfentity_gen: "2.2.0+12"
    #path: /Users/reni/Downloads/Projetos/Flutter/libs/sqfEntity/sqfentity_gen/
    # git:
    #   ref: a445f57844d40a962dd3b3fc2daa92c84c6ffad1
    #   path: sqfentity_gen
    #   url: https://github.com/aynova-tecnologia/sqfEntity.git
  build_verify: ^2.0.0
  mobx_codegen: ^2.0.3
  build_runner: ^2.1.1
  hive_generator: 1.1.1
  flutter_test:
    sdk: flutter
 
flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: br.com.msk.msk
        pluginClass: MskPlugin
      ios:
        pluginClass: MskPlugin
      windows:
        pluginClass: MskPlugin

  assets:
    - imagens/


scripts:
   build: flutter pub run build_runner build --delete-conflicting-outputs
   watch: flutter pub run build_runner watch --delete-conflicting-outputs
   clean: flutter pub run build_runner clean
   release: flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
   profile: flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi --profile

